name = "Sky Siege Industrial"
author = "waigoma"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a01f0c64a7d9077285c7f5a10c466aee21a79902c3ce2b5ae74d856a9dc711e4"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
