name = "Sky Siege Industrial"
author = "waigoma"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10589fa1469231b5fe9bb93f70aedbf181551d51d4ddc78c5106b396d516ec9b"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
