name = "Sky Siege Industrial"
author = "waigoma"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97f5373824fb4fc3352083d5f17d986fc6fdacc6a7e6a94e5698c974ee74028d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
